services:
  - type: worker
    name: auto-wiper-bot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      API_ID: 
        sync: false
      API_HASH:
        sync: false
      BOT_TOKEN:
        sync: false
      CHAT_IDS:
        sync: false
      ID_DUR:
        sync: false
